### PR TITLE
ci: add github actions workflow to run test suite

### PR DESCRIPTION
**Pull request by afuetterer**
Hi, this is my first PR to the project.

This PR adds a minimal GitHub actions workflow to run the test suite with pytest.

But this takes rather long.

I would like to contribute a few more changes, if you like. Please say no, if not.

### CODE REVIEW

**Comment by afuetterer** [comment]
What do you think @hsluytergaethje?

**Comment by hsluytergaethje** [comment]
Thank you for your contribution and the PR, we are happy if more people want to work on pydracor!

**Review by cmil — APPROVED** [review]
Looks good to me.

**Comment by afuetterer** [comment]
As I said, the tests take rather long. The test suite should not run for 20 minutes. :)

**Pull request merged**
